
export const ExperienceCategoryData = {
    id: 1,
    name: "Experience",
    uuid: "304386",
    user_id: 654,
    job_position: "Aerospace Engineer",
    company_name: "abc ltd",
    country_id: 14,
    state: "abc",
    city: "abc",
    type: null,
    start_date: "2004-01-01",
    end_date: null,
    currently_working: 1,
    company_description: null,
    job_description: "hjkh hjkh hjkh hjkh hjkh hjkh hjkh",
    sort: 1,
    status: 1,
};
export const EducationCategoryData = {
    id: 1,
    name: "Education",
    uuid: "304386",
    user_id: 654,
    job_position: "Aerospace Engineer",
    company_name: "abc ltd",
    country_id: 14,
    state: "abc",
    city: "abc",
    type: null,
    start_date: "2004-01-01",
    end_date: null,
    currently_working: 1,
    company_description: null,
    job_description: "hjkh hjkh hjkh hjkh hjkh hjkh hjkh",
    sort: 1,
    status: 1,
};
export const CertificatesCategoryData = {
    id: 1,
    name: "Certificates",
    uuid: "304386",
    user_id: 654,
    job_position: "Aerospace Engineer",
    company_name: "abc ltd",
    country_id: 14,
    state: "abc",
    city: "abc",
    type: null,
    start_date: "2004-01-01",
    end_date: null,
    currently_working: 1,
    company_description: null,
    job_description: "hjkh hjkh hjkh hjkh hjkh hjkh hjkh",
    sort: 1,
    status: 1,
};
export const AwardsCategoryData = {
    id: 1,
    name: "Awards",
    uuid: "304386",
    user_id: 654,
    job_position: "Aerospace Engineer",
    company_name: "abc ltd",
    country_id: 14,
    state: "abc",
    city: "abc",
    type: null,
    start_date: "2004-01-01",
    end_date: null,
    currently_working: 1,
    company_description: null,
    job_description: "hjkh hjkh hjkh hjkh hjkh hjkh hjkh",
    sort: 1,
    status: 1,
};
export const LanguagesCategoryData = {
    id: 1,
    name: "Languages",
    uuid: "304386",
    user_id: 654,
    job_position: "Aerospace Engineer",
    company_name: "abc ltd",
    country_id: 14,
    state: "abc",
    city: "abc",
    type: null,
    start_date: "2004-01-01",
    end_date: null,
    currently_working: 1,
    company_description: null,
    job_description: "hjkh hjkh hjkh hjkh hjkh hjkh hjkh",
    sort: 1,
    status: 1,
};
export const ReferencesCategoryData = {
    id: 1,
    name: "References",
    uuid: "304386",
    user_id: 654,
    job_position: "Aerospace Engineer",
    company_name: "abc ltd",
    country_id: 14,
    state: "abc",
    city: "abc",
    type: null,
    start_date: "2004-01-01",
    end_date: null,
    currently_working: 1,
    company_description: null,
    job_description: "hjkh hjkh hjkh hjkh hjkh hjkh hjkh",
    sort: 1,
    status: 1,
};